In [1]:
import numpy as np
import glob
import scipy.io.wavfile
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [2]:
import librosa
import librosa.display

# Feature Extraction

In [3]:
# All paths of mfcc data.
paths = ['AS_New_308/*.wav', 'MS_New_308/*.wav', 'MR_New_308/*.wav', 'MVP_New_308/*.wav', 'N_New_308/*.wav']
data=[]
entireMfcc = () # Tuple for concatenation proccess.
for path_i in range(len(paths)):
    data = glob.glob(paths[path_i]) # Get index of the path and set the data. 
    temp_mfcc=[]
    for i in range(len(data)):
        sample_rate, signal = scipy.io.wavfile.read(data[i])
        signal = np.float32(signal)
        mfccs = librosa.feature.mfcc(y=signal, sr=sample_rate, n_mfcc=40)
        mfccs = np.mean(mfccs.T,axis=0)
        temp_mfcc.append(np.asarray(mfccs).flatten())
    temp_mfcc = np.asarray(temp_mfcc) # temporary variable for adding the data to "entireMfcc"
    entireMfcc = entireMfcc + (temp_mfcc, ) # In each iteration, the data adding on cumulatively

In [4]:
signal


array([-3., -6., -8., ..., -7., -3., -2.], dtype=float32)

In [5]:
sample_rate

8000

In [6]:
entireMfcc

(array([[ 6.8279718e+02,  1.2874593e+02,  6.9038406e+01, ...,
         -1.8026257e+00, -1.0319037e+00, -6.6541404e-01],
        [ 6.8629834e+02,  1.2640754e+02,  6.7568977e+01, ...,
         -1.4843044e+00, -5.7262665e-01, -4.0649813e-01],
        [ 6.8384570e+02,  1.2675324e+02,  6.9803627e+01, ...,
         -2.0788934e+00, -1.1161417e+00, -6.2415129e-01],
        ...,
        [ 6.4676727e+02,  1.4205522e+02,  7.0697815e+01, ...,
         -1.0535643e+00, -1.5439521e+00, -7.2778249e-01],
        [ 6.3950055e+02,  1.3887318e+02,  7.5332405e+01, ...,
         -1.9518110e+00, -1.6623551e+00, -8.2572103e-01],
        [ 6.2839435e+02,  1.3975009e+02,  7.7321594e+01, ...,
         -1.2842238e+00, -1.1432173e+00, -1.1725806e+00]], dtype=float32),
 array([[635.2525   , 147.34207  ,  62.706978 , ...,  -2.5703359,
          -2.8821661,  -2.9147797],
        [635.64417  , 146.4026   ,  64.669106 , ...,  -2.2961063,
          -3.2466738,  -3.5038316],
        [638.0349   , 142.38412  ,  61.835922 

In [7]:
import pywt

In [8]:
# All paths of dwt data.
paths = ['AS_New_308/*.wav', 'MS_New_308/*.wav', 'MR_New_308/*.wav', 'MVP_New_308/*.wav', 'N_New_308/*.wav']
data=[]
entireDwt = () # Tuple for concatenation proccess.
for path_i in range(len(paths)):
    data = glob.glob(paths[path_i]) # Get index of the path and set the data. 
    temp_dwt=[]
    for i in range(len(data)):
        sample_rate,signal=scipy.io.wavfile.read(data[i]) #Reading Audio
        signal=np.float32(signal)
        cA, cD=pywt.dwt(signal,'haar') #DWT cA->Approximation coeffs cD->Detailed coeffs
        dwts=pywt.idwt(cA, cD,'haar') #IDWT
        dwts = np.mean(dwts.T,axis=0)
        temp_dwt.append(np.asarray(dwts).flatten()) 
    temp_dwt = np.asarray(temp_dwt)
    entireDwt = entireDwt + (temp_dwt, )

In [9]:
cA

array([ -6.3639607, -11.313708 , -10.606602 , ..., -16.263454 ,
       -12.727922 ,  -3.535534 ], dtype=float32)

In [10]:
cD

array([ 2.1213202,  0.       , -0.7071066, ..., -0.7071066, -2.8284268,
       -0.7071067], dtype=float32)

In [11]:
signal

array([-3., -6., -8., ..., -7., -3., -2.], dtype=float32)

In [12]:
entireDwt

(array([[ 45.85981   ],
        [  2.5291996 ],
        [ 41.099125  ],
        [-20.044512  ],
        [-18.769272  ],
        [ 30.658983  ],
        [ 12.850452  ],
        [ 43.059082  ],
        [-14.792654  ],
        [-14.380095  ],
        [-37.498356  ],
        [-31.152365  ],
        [ -9.249523  ],
        [  6.295093  ],
        [ 38.050865  ],
        [ -2.0160398 ],
        [ 70.31656   ],
        [ 44.57936   ],
        [ 26.636286  ],
        [-25.967524  ],
        [-43.236195  ],
        [ 32.70861   ],
        [ 15.02972   ],
        [ -0.7776848 ],
        [-13.5022955 ],
        [ -6.268391  ],
        [  1.4015306 ],
        [-12.728554  ],
        [ 15.84807   ],
        [  9.714309  ],
        [  0.385509  ],
        [  0.17548202],
        [ -1.1467593 ],
        [ -5.0565085 ],
        [  5.0160093 ],
        [  7.450425  ],
        [ -7.9848223 ],
        [ 13.554445  ],
        [-16.60603   ],
        [-11.898633  ],
        [  2.7479243 ],
        [ 11.265

# Concatenation

In [13]:
FeatMFCC = np.concatenate(entireMfcc)

In [14]:
FeatMFCC.shape

(1000, 40)

In [15]:
FeatDWT = np.concatenate(entireDwt)

In [16]:
FeatDWT.shape

(1000, 1)

# Creating a target tag

In [17]:
targets = ()
for i in range(1, 6): 
    x = np.arange(1) + i
    temp_target = x.repeat(200)
    targets = targets + (temp_target, )

In [18]:
targets


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2,

In [19]:
my_target=np.concatenate(targets)


In [20]:
X = FeatMFCC
y = my_target

In [21]:
X

array([[ 6.8279718e+02,  1.2874593e+02,  6.9038406e+01, ...,
        -1.8026257e+00, -1.0319037e+00, -6.6541404e-01],
       [ 6.8629834e+02,  1.2640754e+02,  6.7568977e+01, ...,
        -1.4843044e+00, -5.7262665e-01, -4.0649813e-01],
       [ 6.8384570e+02,  1.2675324e+02,  6.9803627e+01, ...,
        -2.0788934e+00, -1.1161417e+00, -6.2415129e-01],
       ...,
       [ 5.2115186e+02,  1.0983742e+02,  6.5466606e+01, ...,
        -2.5553288e+00, -5.0337470e-01, -1.1908077e-01],
       [ 5.2436407e+02,  1.0691790e+02,  6.1364494e+01, ...,
        -3.5477555e+00, -2.2115829e+00,  2.8561631e-01],
       [ 5.0363693e+02,  9.8301842e+01,  5.6758865e+01, ...,
        -1.4230636e+00, -6.1680353e-01, -8.4923351e-01]], dtype=float32)

# Train_test_split()

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 127)

In [23]:
X_train

array([[ 5.5201392e+02,  1.0541018e+02,  6.5333237e+01, ...,
        -2.5249383e+00, -1.6410459e+00, -1.7133900e+00],
       [ 6.8442316e+02,  1.0520182e+02,  1.9256742e+01, ...,
        -5.0651443e-01,  9.2470998e-01, -3.0562174e-02],
       [ 6.8485840e+02,  1.2401286e+02,  6.7420349e+01, ...,
        -2.2601066e+00, -2.1106489e+00, -9.2061120e-01],
       ...,
       [ 6.0573822e+02,  8.9865829e+01,  4.8795811e+01, ...,
        -3.0022604e+00, -1.7327499e+00, -1.1768028e+00],
       [ 4.8067325e+02,  9.6352615e+01,  6.7179878e+01, ...,
        -1.5443519e+00, -1.8531929e+00, -2.2825594e+00],
       [ 6.3564417e+02,  1.4640260e+02,  6.4669106e+01, ...,
        -2.2961063e+00, -3.2466738e+00, -3.5038316e+00]], dtype=float32)

In [24]:
y_train

array([4, 4, 1, 4, 4, 2, 1, 5, 4, 5, 1, 3, 2, 3, 5, 3, 4, 5, 1, 4, 3, 1,
       4, 3, 5, 1, 5, 5, 1, 4, 4, 2, 3, 2, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1,
       1, 2, 1, 5, 2, 1, 3, 2, 2, 4, 5, 5, 5, 5, 3, 4, 5, 2, 3, 1, 1, 1,
       4, 3, 3, 2, 5, 5, 2, 4, 2, 3, 2, 1, 4, 3, 5, 1, 4, 3, 1, 1, 4, 1,
       5, 2, 5, 2, 1, 5, 4, 5, 1, 2, 3, 1, 2, 4, 5, 2, 4, 4, 3, 2, 5, 3,
       5, 3, 1, 3, 2, 4, 5, 2, 4, 3, 2, 2, 1, 5, 5, 4, 2, 2, 4, 1, 5, 4,
       4, 4, 3, 3, 3, 5, 3, 2, 2, 5, 1, 1, 4, 1, 3, 2, 5, 3, 1, 3, 1, 4,
       2, 3, 4, 3, 4, 1, 5, 5, 5, 2, 2, 2, 5, 5, 5, 3, 1, 1, 3, 2, 1, 2,
       2, 1, 1, 4, 5, 3, 5, 4, 5, 4, 5, 1, 4, 5, 4, 4, 2, 1, 4, 4, 1, 3,
       4, 2, 4, 4, 4, 4, 2, 2, 2, 3, 1, 3, 1, 5, 4, 3, 3, 4, 2, 2, 3, 3,
       1, 3, 2, 4, 5, 4, 5, 1, 2, 1, 3, 5, 3, 1, 4, 1, 1, 2, 2, 1, 1, 5,
       1, 4, 1, 5, 1, 1, 2, 2, 4, 4, 5, 4, 3, 2, 3, 1, 4, 5, 4, 1, 2, 3,
       4, 4, 1, 2, 2, 1, 5, 1, 2, 3, 2, 3, 1, 1, 1, 5, 1, 1, 5, 4, 3, 5,
       5, 4, 3, 3, 5, 4, 3, 4, 3, 5, 5, 1, 2, 5, 3,

# Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaler=scaler.fit_transform(X_train)
X_test_scaler=scaler.fit_transform(X_test)

In [26]:
X_train_scaler

array([[-1.0693163e+00, -9.8597777e-01,  4.7067101e-03, ...,
        -7.7127898e-01, -3.4808871e-01, -4.2353398e-01],
       [ 1.5702617e+00, -9.9655378e-01, -2.7023604e+00, ...,
         5.0554937e-01,  1.4536666e+00,  7.8903139e-01],
       [ 1.5789382e+00, -4.1731380e-02,  1.2732786e-01, ...,
        -6.0374993e-01, -6.7785883e-01,  1.4770457e-01],
       ...,
       [ 1.6776457e-03, -1.7749876e+00, -9.6689326e-01, ...,
        -1.0732266e+00, -4.1248623e-01, -3.6894832e-02],
       [-2.4914925e+00, -1.4457272e+00,  1.1319983e-01, ...,
        -1.5097296e-01, -4.9706510e-01, -8.3365023e-01],
       [ 5.9785265e-01,  1.0947407e+00, -3.4312047e-02, ...,
        -6.2652290e-01, -1.4756117e+00, -1.7136408e+00]], dtype=float32)

# Classification and Prediction

In [27]:
# Training classifiers
clf1 = DecisionTreeClassifier(max_depth=10)
clf2 = KNeighborsClassifier(n_neighbors=5)
clf3 = SVC(gamma=.1, kernel='linear', probability=True)
clf4 = MLPClassifier(random_state=1, max_iter=300)
clf5=RandomForestClassifier(n_estimators=10,criterion="entropy")

In [28]:
clf2 = KNeighborsClassifier()

In [29]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)
clf4.fit(X_train, y_train)
clf5.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [44]:
y1_pred = clf1.predict(X_test)
y2_pred = clf2.predict(X_test)
y3_pred = clf3.predict(X_test)
y4_pred = clf4.predict(X_test)
y5_pred=clf5.predict(X_test)


In [26]:
predictions = [y1_pred, y2_pred, y3_pred, y4_pred, y5_pred]
classifications = [clf1, clf2, clf3, clf4, clf5]
titles = ["Decision Tree Classifier", "KNeighbors Classifier", "SVM Linear Kernel Classifier", "MLP Classifier","Random Forest Classifier" ]
for i in range(len(predictions)):
    result = """
    # {title}\n
    Confusion_Matrix: \n
    {conf_matrix}
    \n Report:\n
    {report}

    Classification Success: {success}
    """.format(title = titles[i],
                conf_matrix = confusion_matrix(y_test, predictions[i]), 
               report = classification_report(y_test, predictions[i]), 
               success = classifications[i].score(X_test, y_test))

    print(result)



    # Decision Tree Classifier

    Confusion_Matrix: 

    [[46  0  3  1  1]
 [ 3 60  1  0  0]
 [ 1  1 56  2  0]
 [ 3  0  2 57  1]
 [ 0  0  0  0 62]]
    
 Report:

                  precision    recall  f1-score   support

           1       0.87      0.90      0.88        51
           2       0.98      0.94      0.96        64
           3       0.90      0.93      0.92        60
           4       0.95      0.90      0.93        63
           5       0.97      1.00      0.98        62

    accuracy                           0.94       300
   macro avg       0.93      0.94      0.93       300
weighted avg       0.94      0.94      0.94       300


    Classification Success: 0.9366666666666666
    

    # KNeighbors Classifier

    Confusion_Matrix: 

    [[47  0  3  1  0]
 [ 2 62  0  0  0]
 [ 6  0 54  0  0]
 [ 1  0  3 59  0]
 [ 0  0  0  0 62]]
    
 Report:

                  precision    recall  f1-score   support

           1       0.84      0.92      0.88        51
          

# Deep Learning

In [27]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
# Encode the classification labels
le = LabelEncoder()
yy = to_categorical(le.fit_transform(y))

Using TensorFlow backend.


In [28]:
# split the dataset 
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, yy, test_size=0.2, random_state = 127)

In [29]:
n_features= X.shape[1] # features: number of columns of our learning data
n_classes = yy.shape[1]
num_labels = yy.shape[1]

In [182]:
# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 256, kernel_initializer = 'uniform', activation = 'relu', input_dim = n_features))
    classifier.add(Dense(units = 128, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 100, batch_size=100)
accuracies = cross_val_score(estimator = classifier, X = x_test, y = y_test)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

Epoch 1/100
640/640 [==============================] - 0s 250us/step - loss: 0.5114 - accuracy: 0.7938
Epoch 2/100
640/640 [==============================] - 0s 64us/step - loss: 0.4198 - accuracy: 0.8169
Epoch 3/100
640/640 [==============================] - 0s 75us/step - loss: 0.3561 - accuracy: 0.8650
Epoch 4/100
640/640 [==============================] - 0s 62us/step - loss: 0.3180 - accuracy: 0.8769
Epoch 5/100
640/640 [==============================] - 0s 63us/step - loss: 0.2817 - accuracy: 0.8850
Epoch 6/100
640/640 [==============================] - 0s 75us/step - loss: 0.2524 - accuracy: 0.8931
Epoch 7/100
640/640 [==============================] - 0s 88us/step - loss: 0.2220 - accuracy: 0.9091 0s - loss: 0.2217 - accuracy: 0.91
Epoch 8/100
640/640 [==============================] - 0s 75us/step - loss: 0.2079 - accuracy: 0.9175
Epoch 9/100
640/640 [==============================] - 0s 63us/step - loss: 0.1901 - accuracy: 0.9234
Epoch 10/100
640/640 [========================

640/640 [==============================] - 0s 62us/step - loss: 0.0234 - accuracy: 0.9944
Epoch 60/100
640/640 [==============================] - 0s 75us/step - loss: 0.0230 - accuracy: 0.9937
Epoch 61/100
640/640 [==============================] - 0s 75us/step - loss: 0.0235 - accuracy: 0.9931
Epoch 62/100
640/640 [==============================] - 0s 63us/step - loss: 0.0219 - accuracy: 0.9937
Epoch 63/100
640/640 [==============================] - 0s 62us/step - loss: 0.0201 - accuracy: 0.9934
Epoch 64/100
640/640 [==============================] - 0s 63us/step - loss: 0.0227 - accuracy: 0.9937
Epoch 65/100
640/640 [==============================] - 0s 62us/step - loss: 0.0280 - accuracy: 0.9897
Epoch 66/100
640/640 [==============================] - 0s 50us/step - loss: 0.0243 - accuracy: 0.9903
Epoch 67/100
640/640 [==============================] - 0s 75us/step - loss: 0.0298 - accuracy: 0.9909
Epoch 68/100
640/640 [==============================] - ETA: 0s - loss: 0.0211 - accur

640/640 [==============================] - 0s 62us/step - loss: 0.1114 - accuracy: 0.9616
Epoch 17/100
640/640 [==============================] - 0s 63us/step - loss: 0.1035 - accuracy: 0.9706
Epoch 18/100
640/640 [==============================] - 0s 75us/step - loss: 0.0931 - accuracy: 0.9719
Epoch 19/100
640/640 [==============================] - 0s 62us/step - loss: 0.0938 - accuracy: 0.9684
Epoch 20/100
640/640 [==============================] - 0s 63us/step - loss: 0.0960 - accuracy: 0.9662
Epoch 21/100
640/640 [==============================] - 0s 62us/step - loss: 0.0842 - accuracy: 0.9725
Epoch 22/100
640/640 [==============================] - 0s 63us/step - loss: 0.0882 - accuracy: 0.9700
Epoch 23/100
640/640 [==============================] - 0s 62us/step - loss: 0.0849 - accuracy: 0.9713
Epoch 24/100
640/640 [==============================] - 0s 62us/step - loss: 0.0806 - accuracy: 0.9697
Epoch 25/100
640/640 [==============================] - 0s 63us/step - loss: 0.0859 - 

640/640 [==============================] - 0s 75us/step - loss: 0.0153 - accuracy: 0.9950
Epoch 74/100
640/640 [==============================] - 0s 63us/step - loss: 0.0164 - accuracy: 0.9950
Epoch 75/100
640/640 [==============================] - 0s 75us/step - loss: 0.0116 - accuracy: 0.9972
Epoch 76/100
640/640 [==============================] - 0s 75us/step - loss: 0.0157 - accuracy: 0.9947
Epoch 77/100
640/640 [==============================] - 0s 62us/step - loss: 0.0222 - accuracy: 0.9922
Epoch 78/100
640/640 [==============================] - 0s 75us/step - loss: 0.0171 - accuracy: 0.9944
Epoch 79/100
640/640 [==============================] - 0s 62us/step - loss: 0.0116 - accuracy: 0.9975
Epoch 80/100
640/640 [==============================] - 0s 50us/step - loss: 0.0173 - accuracy: 0.9937
Epoch 81/100
640/640 [==============================] - 0s 62us/step - loss: 0.0146 - accuracy: 0.9950
Epoch 82/100
640/640 [==============================] - 0s 62us/step - loss: 0.0143 - 

In [30]:
# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 256, kernel_initializer = 'uniform', activation = 'relu', input_dim = n_features))
    classifier.add(Dense(units = 128, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 100, batch_size=100)
accuracies = cross_val_score(estimator = classifier, X = x_test, y = y_test)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

Epoch 1/100
160/160 [==============================] - 2s 12ms/step - loss: 1.6416 - accuracy: 0.1937
Epoch 2/100
160/160 [==============================] - 0s 100us/step - loss: 1.6096 - accuracy: 0.2250
Epoch 3/100
160/160 [==============================] - 0s 106us/step - loss: 1.6038 - accuracy: 0.2250
Epoch 4/100
160/160 [==============================] - 0s 69us/step - loss: 1.6001 - accuracy: 0.2250
Epoch 5/100
160/160 [==============================] - 0s 56us/step - loss: 1.5941 - accuracy: 0.2250
Epoch 6/100
160/160 [==============================] - 0s 118us/step - loss: 1.5858 - accuracy: 0.2250
Epoch 7/100
160/160 [==============================] - 0s 131us/step - loss: 1.5639 - accuracy: 0.2250
Epoch 8/100
160/160 [==============================] - 0s 62us/step - loss: 1.5413 - accuracy: 0.2250
Epoch 9/100
160/160 [==============================] - 0s 59us/step - loss: 1.5345 - accuracy: 0.2250
Epoch 10/100
160/160 [==============================] - 0s 118us/step - loss: 

160/160 [==============================] - 0s 75us/step - loss: 0.3473 - accuracy: 0.9125
Epoch 60/100
160/160 [==============================] - 0s 100us/step - loss: 0.3303 - accuracy: 0.9062
Epoch 61/100
160/160 [==============================] - 0s 106us/step - loss: 0.3273 - accuracy: 0.9250
Epoch 62/100
160/160 [==============================] - 0s 56us/step - loss: 0.3007 - accuracy: 0.9125
Epoch 63/100
160/160 [==============================] - 0s 87us/step - loss: 0.3076 - accuracy: 0.9312
Epoch 64/100
160/160 [==============================] - 0s 62us/step - loss: 0.2923 - accuracy: 0.9062
Epoch 65/100
160/160 [==============================] - 0s 69us/step - loss: 0.2932 - accuracy: 0.9250
Epoch 66/100
160/160 [==============================] - 0s 131us/step - loss: 0.2846 - accuracy: 0.9312
Epoch 67/100
160/160 [==============================] - 0s 62us/step - loss: 0.2804 - accuracy: 0.9250
Epoch 68/100
160/160 [==============================] - 0s 87us/step - loss: 0.2765

160/160 [==============================] - 0s 131us/step - loss: 0.7327 - accuracy: 0.7625
Epoch 39/100
160/160 [==============================] - 0s 50us/step - loss: 0.7154 - accuracy: 0.7688
Epoch 40/100
160/160 [==============================] - 0s 56us/step - loss: 0.7025 - accuracy: 0.7563
Epoch 41/100
160/160 [==============================] - 0s 118us/step - loss: 0.6658 - accuracy: 0.7937
Epoch 42/100
160/160 [==============================] - 0s 50us/step - loss: 0.6295 - accuracy: 0.8000
Epoch 43/100
160/160 [==============================] - 0s 75us/step - loss: 0.6000 - accuracy: 0.8062
Epoch 44/100
160/160 [==============================] - 0s 97us/step - loss: 0.5837 - accuracy: 0.8062
Epoch 45/100
160/160 [==============================] - 0s 75us/step - loss: 0.5219 - accuracy: 0.8438
Epoch 46/100
160/160 [==============================] - 0s 162us/step - loss: 0.5338 - accuracy: 0.8250
Epoch 47/100
160/160 [==============================] - 0s 56us/step - loss: 0.5027

160/160 [==============================] - 0s 94us/step - loss: 0.1903 - accuracy: 0.9438
Epoch 96/100
160/160 [==============================] - 0s 56us/step - loss: 0.1820 - accuracy: 0.9438
Epoch 97/100
160/160 [==============================] - 0s 62us/step - loss: 0.1780 - accuracy: 0.9438
Epoch 98/100
160/160 [==============================] - 0s 94us/step - loss: 0.1782 - accuracy: 0.9500
Epoch 99/100
160/160 [==============================] - 0s 56us/step - loss: 0.1733 - accuracy: 0.9500
Epoch 100/100
40/40 [==============================] - 0s 997us/step
Epoch 1/100
160/160 [==============================] - 0s 1ms/step - loss: 1.6880 - accuracy: 0.1813
Epoch 2/100
160/160 [==============================] - 0s 112us/step - loss: 1.5912 - accuracy: 0.2125
Epoch 3/100
160/160 [==============================] - 0s 93us/step - loss: 1.5967 - accuracy: 0.1750
Epoch 4/100
160/160 [==============================] - 0s 137us/step - loss: 1.5933 - accuracy: 0.1750
Epoch 5/100
160/160 

160/160 [==============================] - 0s 62us/step - loss: 0.2195 - accuracy: 0.9563
Epoch 75/100
160/160 [==============================] - 0s 69us/step - loss: 0.2342 - accuracy: 0.9375
Epoch 76/100
160/160 [==============================] - 0s 69us/step - loss: 0.2085 - accuracy: 0.9375
Epoch 77/100
160/160 [==============================] - 0s 56us/step - loss: 0.2224 - accuracy: 0.9375
Epoch 78/100
160/160 [==============================] - 0s 37us/step - loss: 0.2082 - accuracy: 0.9438
Epoch 79/100
160/160 [==============================] - 0s 56us/step - loss: 0.2042 - accuracy: 0.9438
Epoch 80/100
160/160 [==============================] - 0s 50us/step - loss: 0.2011 - accuracy: 0.9563
Epoch 81/100
160/160 [==============================] - 0s 56us/step - loss: 0.1943 - accuracy: 0.9438
Epoch 82/100
160/160 [==============================] - 0s 94us/step - loss: 0.1838 - accuracy: 0.9500
Epoch 83/100
160/160 [==============================] - 0s 50us/step - loss: 0.1899 - 